//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM13OA.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowInstance
    {
        public WorkflowInstance()
        {
            this.WorkflowStep = new HashSet<WorkflowStep>();
        }
    
        public int InstanceId { get; set; }
        public string InstanceTitle { get; set; }
        public int SubBy { get; set; }
        public System.DateTime SubTime { get; set; }
        public System.Guid InstanceGuid { get; set; }
        public int InstanceState { get; set; }
    
        public virtual ICollection<WorkflowStep> WorkflowStep { get; set; }
    }
}
